version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hello-world"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ttmaw6d1qxfb"
s3_prefix = "hello-world"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
